CREATE USER ORDER_WITH_DATABASES IDENTIFIED BY SYSTEM;
GRANT CREATE SESSION TO ORDER_WITH_DATABASES;
GRANT CREATE TABLE TO ORDER_WITH_DATABASES;
GRANT CREATE SEQUENCE TO ORDER_WITH_DATABASES;
ALTER DATABASE DEFAULT TABLESPACE users;
GRANT UNLIMITED TABLESPACE TO ORDER_WITH_DATABASES;

CREATE SEQUENCE CUSTOMERS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ITEMS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ITEM_GROUPS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ORDERS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE CUSTOMERS
(
CUSTOMER_ID NUMBER(6,0) NOT NULL,
FIRST_NAME VARCHAR2(25 CHAR) NOT NULL,
LAST_NAME VARCHAR2(30 CHAR) NOT NULL,
EMAIL VARCHAR2(60 CHAR) NOT NULL,
STREET_NAME VARCHAR2(80 CHAR) NOT NULL,
STREET_NUMBER VARCHAR2(10 CHAR) NOT NULL,
ZIPCODE VARCHAR2(15 CHAR) NOT NULL,
CITY VARCHAR2(50 CHAR) NOT NULL,
PHONE_NUMBER VARCHAR2(25 CHAR) NOT NULL,
CONSTRAINT customers_pk PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ITEMS
(
ITEM_ID NUMBER(6,0) NOT NULL,
ITEM_NAME VARCHAR2(100 CHAR) NOT NULL,
ITEM_DESCRIPTION VARCHAR2(400 CHAR) NOT NULL,
ITEM_PRICE NUMBER(10,2) NOT NULL,
AMOUNT NUMBER(6,0) NOT NULL,
CONSTRAINT items_pk PRIMARY KEY (ITEM_ID)
);

CREATE TABLE ORDERS
(
ORDER_ID NUMBER(6,0) NOT NULL,
CUSTOMER_ID NUMBER(6,0) NOT NULL,
CONSTRAINT orders_pk PRIMARY KEY (ORDER_ID),
CONSTRAINT orders_customers_fk FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE ITEM_GROUPS
(
ITEM_GROUP_ID NUMBER(6,0) NOT NULL,
ITEM_ID NUMBER(6,0) NOT NULL,
AMOUNT NUMBER(6,0) NOT NULL,
SHIPPING_DATE DATE NOT NULL,
ORDER_ID NUMBER(6,0) NOT NULL,
ITEM_PRICE_WHEN_ORDERED NUMBER(10,2) NOT NULL,
CONSTRAINT item_groups_pk PRIMARY KEY (ITEM_GROUP_ID),
CONSTRAINT item_groups_items_fk FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID),
CONSTRAINT item_groups_orders_fk FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

DROP TABLE CUSTOMERS;
DROP TABLE ITEMS;
DROP TABLE ITEM_GROUPS;
DROP TABLE ORDERS;